# Generated by Django 4.2.9 on 2024-02-01 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("UserID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("MembershipDate", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("BookID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=255)),
                ("ISBN", models.CharField(max_length=13, unique=True)),
                ("PublishedDate", models.DateField()),
                ("Genre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BookDetails",
            fields=[
                ("DetailsID", models.AutoField(primary_key=True, serialize=False)),
                ("NumberOfPages", models.PositiveIntegerField()),
                ("Publisher", models.CharField(max_length=255)),
                ("Language", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BorrowedBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BorrowDate", models.DateField()),
                ("ReturnDate", models.DateField(blank=True, null=True)),
                (
                    "BookID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management_system.book",
                    ),
                ),
                (
                    "UserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="management_system.bookdetails",
            ),
        ),
    ]
