# Generated by Django 4.2.9 on 2024-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
